compras/urls.py
from django.urls import path

from . import views

app_name = 'compras'
urlpatterns = [
    path('carrinho/', views.view_carrinho, name='view_carrinho'),
    path('carrinho/<int:id_NumeroDaSorte>/delete',
         views.delete_do_carrinho, name='delete_do_carrinho'),
    path('<int:anuncio_id>/analisar/',
         views.view_pagina_vendas, name='view_pagina_vendas'),
]

firstapp/urls.py
from django.urls import path

from . import views

app_name = 'firstapp'
urlpatterns = [
    # ex: /firstapp/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /firstapp/algum_id
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /firstapp/algum_id/result
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /firstapp/algum_id/vote
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

rifaki_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('', include('teste_rifaki.urls')),
    path('firstapp/', include('firstapp.urls')),
    path('admin/', admin.site.urls),
    path('cadastro/', include('cadastro.urls')),
    path('', include("django.contrib.auth.urls")),
    path('compras/', include("compras.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(r'media/(?P<path>.*)$',
            serve, {'document_root':
                    settings.MEDIA_ROOT, }),
    ]

firstapp/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

firstapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse , Http404, HttpResponseRedirect
from django.views import generic
from django.urls import reverse

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'firstapp/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'firstapp/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'firstapp/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        select_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'firstapp/detail.html', {
            'question': question,
            'error_message': "Você não selecionou uma resposta"
        })
    else:
        select_choice.votes +=1
        select_choice.save()
        return HttpResponseRedirect(reverse('firstapp:results', args=(question.id,)))













""" def index(request):
    lastest_questions_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': lastest_questions_list}
    return render(request, 'firstapp/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'firstapp/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'firstapp/results.html', {'question': question}) """

firstapp/templates/firstapp/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'firstapp:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

firstapp/templates/firstapp/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="/firstapp/{{question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

firstapp/templates/firstapp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'firstapp:detail' question.id %}">Vote again?</a>