cadastro/urls.py
from django.urls import path

from . import views

app_name = 'cadastro'
urlpatterns = [
    path('user/', views.create_user, name='create_user'),
    path('anuncio/', views.cadastro_anuncio, name='cadastro_anuncio'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('<int:anuncio_id>/edit/',
         views.edit_anuncio, name='edit_anuncio'),
    path('profile/password/', views.edit_password, name='edit_password'),
    path('categorias/', views.cria_categoria, name='cria_categoria'),
    path('categorias/list/', views.view_categorias, name='view_categorias'),
    path('categorias/list/<int:categoria_id>/delete/',
         views.delete_categoria, name='delete_categoria'),
    path('categorias/list/<int:categoria_id>/edit/',
         views.edit_categoria, name='edit_categoria'),
]

compras/urls.py
from django.urls import path

from . import views

app_name = 'compras'
urlpatterns = [
    path('carrinho/', views.view_carrinho, name='view_carrinho'),
    path('carrinho/<int:id_NumeroDaSorte>/delete',
         views.delete_do_carrinho, name='delete_do_carrinho'),
    path('<int:anuncio_id>/analisar/',
         views.view_pagina_vendas, name='view_pagina_vendas'),
]

rifaki_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('', include('teste_rifaki.urls')),
    path('firstapp/', include('firstapp.urls')),
    path('admin/', admin.site.urls),
    path('cadastro/', include('cadastro.urls')),
    path('', include("django.contrib.auth.urls")),
    path('compras/', include("compras.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(r'media/(?P<path>.*)$',
            serve, {'document_root':
                    settings.MEDIA_ROOT, }),
    ]

teste_rifaki/urls.py
from django.urls import path

from . import views

app_name = 'teste_rifaki'
urlpatterns = [
    # ex: /teste_rifaki/
    path('', views.index, name='index'),
    # ex: /teste_rifaki/<algum id>
    path('<int:anuncio_id>/', views.detail_anuncio, name='detail'),
    #     # ex: /teste_rifaki/cadastro_anuncio
    path('anuncios/', views.view_profile_anuncios,
         name='view_profile_anuncios'),
]


"""     # ex: /firstapp/algum_id
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /firstapp/algum_id/result
    path('<int:question_id>/result/', views.results, name='result'),
    # ex: /firstapp/algum_id/vote
    path('<int:question_id>/vote/', views.vote, name='vote'), """

teste_rifaki/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from cadastro.models import Anuncio

teste_rifaki/forms.py
from django import forms

from .models import Categoria


# class CadastraAnuncio(forms.ModelForm):

#     class Meta:
#         model = Anuncio
#         fields = ('titulo_anuncio', 'descricao_breve', 'descricao_completa',
#                   'imagem1', 'imagem2', 'imagem3', 'imagem4', 'imagem5')

teste_rifaki/views.py
from django.shortcuts import render, get_object_or_404
from cadastro.views import Anuncio
from teste_rifaki.myClasses import Categoria, Expositor, ControladorCategorias, ControladorExpositor, Pesquisador
from compras.models import NumeroDaSorte, Carrinho


from django.utils import timezone

# adicionar os dois metodos a baixo ao contrutor para ja ser executado na criacao
controlador_expositores = ControladorExpositor()
pesquisador = Pesquisador()


def index(request):
    # sem parametro preenche o expositor index
    controlador_expositores.preencheExpositores()

    # inutilzada pq ainda não sei como atualizar os anuncios que foram modificados
    # controlador_expositores.atualizaExpositoresIndex()
    # controlador_expositores.preencheExpositores()          criar metodo atualizar que não renderiza tudo de novo

    context = {'controlador_expositores': controlador_expositores}

    if request.user.is_authenticated:
        users_carrinho = Carrinho.objects.get(proprietario=request.user)
        itens = users_carrinho.itens.all()
        context['users_carrinho'] = users_carrinho
        context['itens_no_carrinho'] = itens

    query = ''
    resultados = None
    if request.GET:
        # print(request.GET)
        query = request.GET['q']
        context['query'] = str(query)
        resultados = pesquisador.pesquisaPraMim(query)
        expositores_pesquisa = controlador_expositores.preencheExpositores(
            data=resultados)

        context['resultados'] = resultados
        print(resultados)

    return render(request, 'teste_rifaki/html/index.html', context)


def detail_anuncio(request, anuncio_id):
    anuncio = get_object_or_404(Anuncio, pk=anuncio_id)

    usuario = request.user
    context = {'anuncio': anuncio, 'usuario': usuario}

    if usuario.is_authenticated:
        users_carrinho = Carrinho.objects.get(proprietario=usuario)
        itens = users_carrinho.itens.all()
        context['users_carrinho'] = users_carrinho
        context['itens_no_carrinho'] = itens

        if request.method == "POST":
            list_numeros_selecionados = request.POST['num_selected'].split(',')
            # enviar uma caixa de alerta de sucesso para o comprador "Seus números foram colocados no carrinho" -------------------- To Do
            print('lista de numeros enviados para o carrinho: ' +
                  str(list_numeros_selecionados))

            for numero in list_numeros_selecionados:
                numero_da_sorte = NumeroDaSorte()
                numero_da_sorte.numero_escolhido = int(numero)
                numero_da_sorte.anuncio_escolhido = anuncio
                numero_da_sorte.comprador = usuario
                numero_da_sorte.save()
                users_carrinho.itens.add(numero_da_sorte)
                users_carrinho.data_ultima_modificacao = timezone.now()
                users_carrinho.save()

    return render(request, 'teste_rifaki/html/detail.html', context)


def view_profile_anuncios(request):
    context = {'controlador_expositores': controlador_expositores}

    if request.user.is_authenticated:
        users_carrinho = Carrinho.objects.get(proprietario=request.user)
        itens = users_carrinho.itens.all()
        context['users_carrinho'] = users_carrinho
        context['itens_no_carrinho'] = itens

    if request.user.is_authenticated:
        expositores = controlador_expositores.preencheExpositores(
            data=request.user)
        context['expositores'] = expositores
        return render(request, 'teste_rifaki/html/view_anuncios.html', context)
    else:
        return redirect('/login')

teste_rifaki/templates/teste_rifaki/html/index.html
{% extends 'teste_rifaki/html/base.html' %} {% load static %}

{% load crispy_forms_tags %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'teste_rifaki/styles/index.css' %}">
{% endblock head %}


{% block main %}
    {% comment %} <div id="main" class="index"> {% endcomment %}
{% endblock main %}


{% block content %}
    <!-- SLIDE DESTAQUES -->
    <div id="carouselExampleIndicators" class="carousel slide" > {% comment %} data-ride="carousel" {% endcomment %}
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active" style="width: 100%;">
                <div class="img-container">
                    <img class='d-block w-100 imagem-slideshow' src="{% static 'teste_rifaki/imagens/carros/fusca4.jpeg' %}" alt="">
                </div>
                <div class="desc-destaque uk-card-hover uk-card uk-card-default uk-card-body uk-card-small">
                    <div class="uk-card-body card-body">
                        <h1>Fusca 1964</h1>
                        <h2>Motor 1.7 Caveira, <br />Roda Roletada</h2>
                    </div>
                    <div class="uk-card-footer">
                        <h1>R$35,00</h1>
                        <button
                            class="uk-button uk-button-secondary uk-text-uppercase  uk-button-large uk-text-bold btn-mine">testar
                            a sorte</button>
                    </div>
                </div>
            </div>
            <div class="carousel-item" style="width: 100%;">
                <img class='d-block w-100 imagem-slideshow' src="{% static 'teste_rifaki/imagens/carros/chevete sl.jpg' %}" alt="" >
                <div class="desc-destaque uk-card-hover uk-card uk-card-default uk-card-body uk-card-small">
                    <div class="uk-card-body card-body">
                        <h1>Chevette SL <br />1978</h1>
                        <h2>Rodas ProStar</h2>
                    </div>
                    <div class="uk-card-footer">
                        <h1>R$45,00</h1>
                        <button
                            class="uk-button uk-button-secondary uk-text-uppercase  uk-button-large uk-text-bold btn-mine">testar
                            a sorte</button>
                    </div>
                </div>
                {% comment %} <div class="desc-destaque-m uk-card-hover uk-card uk-card-default uk-card-body uk-card-small uk-hidden@s">
                    <div class="uk-card-body" style='padding:0px !important;'>
                        <h1>Chevette SL <br/> 1978</h1>
                        <h2>Rodas ProStar</h2>
                    </div>
                    <div class="uk-card-footer card-footer-m">
                        <h1>R$45,00</h1>
                        <button
                            class="uk-button uk-button-secondary uk-text-uppercase uk-button-small uk-text-bold btn-mine">testar
                            a sorte</button>
                    </div>
                </div> {% endcomment %}

            </div>
            <a class="carousel-control-prev controle-slideshow-e" href="#carouselExampleIndicators" role="button" data-slide="prev"  >
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next controle-slideshow-d" href="#carouselExampleIndicators" role="button" data-slide="next" >
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    <!-- GRADIENTE -->
    <div class="faixa-gradiente-destaques">
    </div>
    {% if resultados != None %}

        {% if resultados %}
            <ul class='c1' style='list-style:none;'>
                <a href='/'>
                    <ul class='comando-voltarr'>
                        <li><span class="carousel-control-prev-icon v-icon" aria-hidden="true"> </span></li>
                        <li class='voltar'><h1 class='btn-voltar'>VOLTAR</h1></li>
                    </ul>
                </a>
                <li><h1 class='result-pesquisa'> Resultados da pesquisa: </h1></li>
            </ul>
            {% for expositor in controlador_expositores.getListaExpositores %}
                {% if expositor.getAnuncios %}
                    <div class="uk-position-relative uk-visible-toggle slider-meu " tabindex="-1" uk-slider>
                        <button
                            class="btn-secoes uk-button uk-button-secondary uk-text-uppercase uk-button-large">{{expositor.getNomeApresentavelCategoria}}</button>
                        <ul class="uk-slider-items uk-child-width-auto uk-dark uk-slider-meu">
                            {% for anuncio in expositor.getAnuncios %}
                            <li class="uk-transition-toggle" tabindex="0">
                                <a href="/{{anuncio.id}}/">
                                    <img class='imagem-slider' src="" data-src="media/{{anuncio.getFirstImage}}" alt="">
                                </a>
                                <a href="/{{anuncio.id}}/">
                                    <div class="uk-overlay uk-overlay-default uk-position-bottom card-desc-meu">
                                        <h1>{{anuncio.titulo_anuncio}}</h1>
                                        <h2></h2>
                                        <button class="uk-button uk-button-primary uk-position-bottom-center btn-secoes" ><a class='uk-position-center ' uk-icon="chevron-down" href="/{{anuncio.id}}/">R${{anuncio.preco}}</a></button>
                                    </div>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>

                        <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous
                            uk-slider-item="previous"></a>
                        <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next
                            uk-slider-item="next"></a>
                        <ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin dotnav-meu"></ul>
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <ul class='c1' style='list-style:none;'>
                <a href='/'>
                    <ul class='comando-voltarr'>
                        <li><span class="carousel-control-prev-icon v-icon" aria-hidden="true"> </span></li>
                        <li class='voltar'><h1 class='btn-voltar'>VOLTAR</h1></li>
                    </ul>
                </a>
                <li><h1 class='result-pesquisa'> Infelizmente sua pesquisa não gerou resultados! </h1></li>
            </ul>
        {% endif %}    

    {% else %}

        <!-- expositores -->
        {% for expositor in controlador_expositores.getListaExpositores %}
            {% if expositor.getAnuncios %}
                <div class="uk-position-relative uk-visible-toggle slider-meu " tabindex="-1" uk-slider>
                    <button
                        class="btn-secoes uk-button uk-button-secondary uk-text-uppercase uk-button-large">{{expositor.getNomeApresentavelCategoria}}</button>
                    <ul class="uk-slider-items uk-child-width-auto uk-dark uk-slider-meu">
                        {% for anuncio in expositor.getAnuncios %}
                        <li class="uk-transition-toggle" tabindex="0">
                            <a href="/{{anuncio.id}}/"><img class='imagem-slider' src="" data-src="media/{{anuncio.getFirstImage}}" alt=""></a>
                            <div class="uk-overlay uk-overlay-default uk-position-bottom card-desc-meu">
                                <h1>{{anuncio.titulo_anuncio}}</h1>
                                <h2></h2>
                                <button class="uk-button uk-button-primary uk-position-bottom-center btn-secoes" ><a class='uk-position-center ' uk-icon="chevron-down" href="/{{anuncio.id}}/">R${{anuncio.preco}}</a></button>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>

                    <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous
                        uk-slider-item="previous"></a>
                    <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next
                        uk-slider-item="next"></a>
                    <ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin dotnav-meu"></ul>
                </div>
            {% endif %}
        {% endfor %}

    {% endif %}

    
    

{% endblock content %}


{% block footer %}

{% endblock footer %}


{% block script %}
    <script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@16.0.0/dist/lazyload.min.js"></script>
    
    <script> 
        var lazyLoadInstance = new LazyLoad({
            elements_selector: ".imagem-slider"
        });
    
    </script>
{% endblock script %}

teste_rifaki/templates/teste_rifaki/html/view_anuncios.html
{% extends 'teste_rifaki/html/base.html' %} {% load static %}

{% load crispy_forms_tags %}



{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'teste_rifaki/styles/index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'teste_rifaki/styles/view_anuncios.css' %}">
{% endblock head %}


{% block main %}
    {% comment %} <div id="main" class="meus-anuncios">  {% endcomment %}
{% endblock main %}


{% block content %}
{% if controlador_expositores.numeroDeAnunciosNosExpositores %}
    {% for expositor in controlador_expositores.getListaExpositores %}
        {% if expositor.getAnuncios %}
            <div class="uk-position-relative uk-visible-toggle slider-principais-meu" tabindex="-1" uk-slider>
                <button
                    class="btn-mine uk-button uk-button-secondary uk-text-uppercase uk-button-large">{{expositor.getNomeApresentavelCategoria}}</button>
                <ul class="uk-slider-items uk-child-width-auto uk-dark uk-slider-meu">
                    {% for anuncio in expositor.getAnuncios %}
                        <div class='card-anuncio'>
                            <li class="uk-transition-toggle flex-align-center" tabindex="0">
                                <a href="/{{anuncio.id}}/"><img class='imagem-slider' src='' data-src="media/{{anuncio.getFirstImage}}" alt=""></a>
                                {% comment %} <div class="uk-overlay uk-overlay-default uk-position-bottom card-desc-meu">
                                    <h1>{{anuncio.titulo_anuncio}}</h1>
                                    <h2></h2>
                                    <button class="uk-button uk-button-primary uk-position-bottom-center"><a class='uk-text-uppercase' href="/cadastro/{{anuncio.id}}/edit/">editar</a></button>
                                </div> {% endcomment %}
                            </li>
                            <div class='anuncio-infos'>
                                <h1 class='titulo'>{{anuncio.titulo_anuncio}}</h1>
                                <h2></h2>
                                <div class='group-buttons'>
                                    <button class="uk-button uk-button-primary black-button "><a class='texto-grey-button' href="/cadastro/{{anuncio.id}}/edit/">editar</a></button>
                                    <button class="uk-button uk-button-primary black-button "><a class='texto-grey-button' href="/compras/{{anuncio.id}}/analisar/">analisar</a></button>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </ul>

                <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous
                    uk-slider-item="previous"></a>
                <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next
                    uk-slider-item="next"></a>
                <ul class="uk-slider-nav uk-dotnav uk-flex-center uk-margin"></ul>
            </div>
        {% endif %}
    {% endfor %}
{% else %}
    <div class='centered-message'>
        <h1> Você não possui anúncios publicados! </h1>
    </div>

{% endif %}


{% endblock  %}


{% block footer %}
        
{% endblock footer %}

{% block script %}
    <script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@16.0.0/dist/lazyload.min.js"></script>
    
    <script> 
        var lazyLoadInstance = new LazyLoad({
            elements_selector: ".imagem-slider"
        
        });
    
    </script>
{% endblock script %}
{% comment %} ="{% url 'cadastro:edit_anuncio' %} {% endcomment %}