cadastro/urls.py
from django.urls import path

from . import views

app_name = 'cadastro'
urlpatterns = [
    path('user/', views.create_user, name='create_user'),
    path('anuncio/', views.cadastro_anuncio, name='cadastro_anuncio'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('<int:anuncio_id>/edit/',
         views.edit_anuncio, name='edit_anuncio'),
    path('profile/password/', views.edit_password, name='edit_password'),
    path('categorias/', views.cria_categoria, name='cria_categoria'),
    path('categorias/list/', views.view_categorias, name='view_categorias'),
    path('categorias/list/<int:categoria_id>/delete/',
         views.delete_categoria, name='delete_categoria'),
    path('categorias/list/<int:categoria_id>/edit/',
         views.edit_categoria, name='edit_categoria'),
]

compras/urls.py
from django.urls import path

from . import views

app_name = 'compras'
urlpatterns = [
    path('carrinho/', views.view_carrinho, name='view_carrinho'),
    path('carrinho/<int:id_NumeroDaSorte>/delete',
         views.delete_do_carrinho, name='delete_do_carrinho'),
    path('<int:anuncio_id>/analisar/',
         views.view_pagina_vendas, name='view_pagina_vendas'),
]

rifaki_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('', include('teste_rifaki.urls')),
    path('firstapp/', include('firstapp.urls')),
    path('admin/', admin.site.urls),
    path('cadastro/', include('cadastro.urls')),
    path('', include("django.contrib.auth.urls")),
    path('compras/', include("compras.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(r'media/(?P<path>.*)$',
            serve, {'document_root':
                    settings.MEDIA_ROOT, }),
    ]

compras/models.py
from django.db import models
from django.contrib.auth.models import User
from cadastro.models import Anuncio


class NumeroDaSorte(models.Model):
    numero_escolhido = models.IntegerField()
    anuncio_escolhido = models.ForeignKey(Anuncio, on_delete=models.CASCADE)
    comprador = models.ForeignKey(
        User, on_delete=models.CASCADE)


class Carrinho(models.Model):
    proprietario = models.ForeignKey(User, on_delete=models.CASCADE)
    data_ultima_modificacao = models.DateTimeField()
    itens = models.ManyToManyField(NumeroDaSorte)


class Venda(models.Model):
    comprador_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='comprador')
    vendedor_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='vendedor')
    data_de_registro = models.DateTimeField()
    numero_vendido = models.ForeignKey(NumeroDaSorte, on_delete=models.CASCADE)
    valor = models.DecimalField(decimal_places=2, max_digits=8)

compras/forms.py
from django.shortcuts import get_object_or_404
from django import forms
from django.contrib.auth.models import User
from cadastro.models import Anuncio, Categoria
from .models import Venda, NumeroDaSorte, Carrinho


class DateInput(forms.DateInput):
    input_type = 'date'


class FormRegisterVenda(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.controlador = kwargs.pop('controlador_vendas')
        super(FormRegisterVenda, self).__init__(*args, **kwargs)

    username = forms.CharField(
        max_length=100, label="Username do comprador:")

    data_de_registro = forms.DateField(
        widget=(DateInput()), label="Data da venda:")

    numero_vendido_form = forms.IntegerField(label="Digite o número vendido:")

    class Meta:
        model = Venda
        fields = [
            'username',
            'numero_vendido_form',
            'data_de_registro',
        ]

    def clean_numero_vendido_form(self):
        numero_vendido_form = self.cleaned_data.get("numero_vendido_form")
        if len(str(numero_vendido_form)) != 3:
            raise forms.ValidationError(
                "Digite o número em um formato valido, com três digitos. Ex.: 005"
            )
        if numero_vendido_form not in self.controlador.getListaNumRestantes:
            raise forms.ValidationError(
                "Desculpe, este número já esta registrado como vendido em nosso sistema!"
            )
        return numero_vendido_form

    def clean_username(self):
        username = self.cleaned_data.get('username')

        try:
            user = get_object_or_404(User, username=username)
        except:
            raise forms.ValidationError(
                'Este usuario não esta cadastrado em nosso sistema!'
            )


# class FormRegisterVenda(forms.ModelForm):

#     """ def __init__(self, *args, **kwargs):
#         self.controlador = kwargs.pop('controlador_vendas')
#         super(FormRegisterVenda, self).__init__(*args, **kwargs) """

#     username = forms.CharField(
#         max_length=100, label="Username do comprador:")

#     data_de_registro = forms.DateField(
#         widget=(DateInput()), label="Data da venda:")

#     numero_vendido_form = forms.IntegerField(label="Digite o número vendido:")

#     class Meta:
#         model = Venda
#         fields = [
#             'username',
#             'numero_vendido_form',
#             'data_de_registro',
#         ]

#     def clean_numero_vendido_form(self, *args, **kwargs):
#         cleaned_data = self.clean()
#         numero = cleaned_data.get("numero_vendido_form")
#         print(numero)
#         # print(self.controlador.getListaNumRestantes)
#         if len(str(numero)) == 3:
#             return numero
#         else:
#             self.add_error('shortcodeurl', "The url is not valid")
#             # raise forms.ValidationError(
#             #     "Digite o número em um formato valido, com três digitos. Ex.: 005"
#             # )
#         # if numero not in self.controlador.getListaNumRestantes:
#         #     raise forms.ValidationError(
#         #         "Desculpe, este número já esta registrado como vendido em nosso sistema!"
#         #     )

compras/views.py
from .models import Carrinho, NumeroDaSorte
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from .myClasses import ControladorDeCompras
from cadastro.models import Anuncio
from .forms import FormRegisterVenda
from django.contrib.auth.models import User


controlador_vendas = ControladorDeCompras()

# ------------- CARRINHO PAGE'S VIEWS --------------- #


def view_carrinho(request):
    context = {}
    if request.user.is_authenticated:
        try:
            users_carrinho = Carrinho.objects.get(proprietario=request.user)
            itens = users_carrinho.itens.all()
            context['users_carrinho'] = users_carrinho
            context['itens_no_carrinho'] = itens
        except:
            carrinho = Carrinho()
            carrinho.proprietario = request.user
            carrinho.data_ultima_modificacao = timezone.now()
            carrinho.save()

            itens = users_carrinho.itens.all()
            context['users_carrinho'] = users_carrinho
            context['itens_no_carrinho'] = itens

            print('Criamos um carrinho pra ti!')

        return render(request, 'compras/view_pages/view_carrinho.html', context)
    else:
        return redirect('/login')


def delete_do_carrinho(request, id_NumeroDaSorte):
    numero_excluido = get_object_or_404(NumeroDaSorte, pk=id_NumeroDaSorte)
    if numero_excluido.comprador == request.user:
        numero_excluido.delete()

        return HttpResponseRedirect(reverse('compras:view_carrinho'))
    else:
        redirect('compras:view_carrinho')


# ------------- ANALISE PAGE'S VIEWS --------------- #
def view_pagina_vendas(request, anuncio_id):
    anuncio = get_object_or_404(Anuncio, pk=anuncio_id)
    numeros_da_sorte = NumeroDaSorte.objects.filter(anuncio_escolhido=anuncio)

    if anuncio.anunciante == request.user:
        controlador_vendas.getTheNumbersOfAnuncio(anuncio)

        if request.method == "POST":
            form = FormRegisterVenda(
                request.POST, controlador_vendas=controlador_vendas)

            if form.is_valid():

                venda = form.save(commit=False)

                comprador = get_object_or_404(
                    User, username=request.POST['username'])
                venda.comprador_user = comprador

                venda.vendedor_user = request.user

                venda.data_de_registro = request.POST['data_de_registro']

                for number in numeros_da_sorte:
                    if number.numero_escolhido == int(request.POST['numero_vendido_form']):
                        venda.numero_vendido = number

                venda.valor = anuncio.preco

                # venda.save()

                form = FormRegisterVenda(
                    controlador_vendas=controlador_vendas)
                context = {
                    'form': form,
                    'anuncio': anuncio,
                    'controlador_vendas': controlador_vendas,
                }

                return render(request, 'compras/view_pages/view_pagina_vendas.html', context)
        else:
            form = FormRegisterVenda(controlador_vendas=controlador_vendas)

        context = {
            'form': form,
            'anuncio': anuncio,
            'controlador_vendas': controlador_vendas,
        }
        return render(request, 'compras/view_pages/view_pagina_vendas.html', context)
    else:
        return redirect('/')

compras/templates/compras/view_pages/view_carrinho.html
{% extends 'teste_rifaki/html/base.html' %}  {% load static %}

{% load crispy_forms_tags %}


{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'cadastro/styles/form-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'compras/styles/view_carrinho.css' %}">
{% endblock head %}


{% block main %}

{% endblock main %}


{% block content %}

    <div class='container-tabela'>

        {% if users_carrinho %}

            <div class='page-top-content' style='margin-top: 60px;text-align:center;' >
                <h2>Seu carrinho</h2>
                <h3>Ultima modificação feita em: {{users_carrinho.data_ultima_modificacao}}</h3>
            </div>

            <div class='page-list-content'>
                <div class='container-itens-list'>
                    {% if itens_no_carrinho %}
                        <div class='row-titulo'>
                            <h1 class='label-imagens'>Imagem</h1>
                            <h1 class='label-about'>Sobre o anúncio</h1>
                            <label class='preco-do-numero'>Preço</label>
                        </div>  
                    {% comment %} <div class='item-card'>
                        <img class='miniatura-anuncio' src="{% static 'teste_rifaki/imagens/carros/fusca4.jpeg' %}">
                        <div class='anuncio-name-and-description'>
                            <h1 class='titulo-anuncio'>Teste ahuahuhsuahsuhaushaushauhsuahsua</h1>
                            <p class='uk-text-justify descricao-anuncio'>Descrição breve Descrição breve Descrição breve Descrição breve Descrição breve Descrição breve</p>
                        </div>
                        <label class='preco-do-numero'>R$10.00</label>
                        <button type="submit" id='btn-excluir' class="btn-excluir-anuncio uk-button uk-button-primary"><a href='' class='texto-btn-excluir'>Excluir</a></button>
                    </div>
                    <div class='item-card'>
                        <img class='miniatura-anuncio' src="{% static 'teste_rifaki/imagens/carros/fusca4.jpeg' %}">
                        <div class='anuncio-name-and-description'>
                            <h1 class='titulo-anuncio'>Teste</h1>
                            <p class='uk-text-justify descricao-anuncio'>Descrição breve Descrição breve Descrição breve Descrição breve Descrição breve Descrição breve</p>
                        </div>
                        <label class='preco-do-numero'>R$10.00</label>
                        <button type="submit" id='btn-excluir' class="btn-excluir-anuncio uk-button uk-button-primary"><a href='' class='texto-btn-excluir'>Excluir</a></button>
                    </div>
                    <div class='item-card'>
                        <img class='miniatura-anuncio' src="{% static 'teste_rifaki/imagens/carros/fusca4.jpeg' %}">
                        <div class='anuncio-name-and-description'>
                            <h1 class='titulo-anuncio'>Teste</h1>
                            <p class='uk-text-justify descricao-anuncio'>Descrição breve Descrição breve Descrição breve Descrição breve Descrição breve Descrição breve</p>
                        </div>
                        <label class='preco-do-numero'>R$10.00</label>
                        <button type="submit" id='btn-excluir' class="btn-excluir-anuncio uk-button uk-button-primary"><a href='' class='texto-btn-excluir'>Excluir</a></button>
                    </div> {% endcomment %}

                    
                        {% for item in itens_no_carrinho %}
                            <div class='item-card'>
                                 <a href="/{{item.anuncio_escolhido.id}}/"><img class='miniatura-anuncio' src="media/{{item.anuncio_escolhido.getFirstImage}}"></a>
                                <div class='anuncio-name-and-description'>
                                    <h1 class='titulo-anuncio'>{{item.anuncio_escolhido.titulo_anuncio}}</h1>
                                    <p class='uk-text-justify descricao-anuncio'>{{item.anuncio_escolhido.descricao_breve}}</p>
                                </div>
                                <label class='preco-do-numero'>R${{item.anuncio_escolhido.preco}}</label>
                                <button type="submit" id='btn-excluir' class="btn-excluir-anuncio uk-button uk-button-primary"><a href="{{item.id}}/delete" class='texto-btn-excluir'>Excluir</a></button>
                            </div>
                        {% endfor %}
                    {% else %}
                        <h2 class='alert-carrinho-vazio'>Seu carrinho está vazio, aproveite para testar sua sorte, corra e garanta já seus números!</h2>    
                    {% endif %}


                    {% comment %} <table class="uk-table table">
                        <tbody class='informacoes-user' style='list-style:none;'>
                            
                            {% if itens_no_carrinho %}
                                <tr class='table-carrinho-row-c'>
                                    <td class='row-titulo-c uk-text-uppercase'>Veículo</td>
                                    <td class='row-titulo-c uk-text-uppercase'>número escolhido</td>
                                    <td class='row-titulo-c uk-text-uppercase'>preço</td>
                                    <td class='row-titulo-c uk-text-uppercase'></td>
                                </tr>
                                {% for itens in itens_no_carrinho %}
                                    <tr class='table-carrinho-row-c'>            
                                        <td class='item-info-c uk-text-uppercase' >{{itens.anuncio_escolhido.titulo_anuncio}}</td>
                                        <td class='item-info-c uk-text-uppercase' >{{itens.numero_escolhido}}</td>
                                        <td class='item-info-c uk-text-uppercase' ></td>
                                        <td class='btn-excluir-carrinho'><button type="submit" id='btn-excluir' class="btn-excluir-anuncio uk-button uk-button-primary"><a href='' class='nome uk-text-uppercase'>Excluir</a></button></td>
                                    </tr>
                                {% endfor %} 
                                <tr>            
                                </tr>
                            {% else %}
                                <tr>            
                                    <td class='item-info-c uk-text-uppercase'>seu carrinho está vazio, aproveite para testar sua sorte, corra e garanta já seus números da sorte!</td>
                                </tr>
                            {% endif %}
                        </tbody>  
                    </table> {% endcomment %}
                    {% if itens_no_carrinho %}
                        <button type="submit" id='btn-finalizar' class="uk-button uk-button-primary btn-finalizar"><a href={% url 'cadastro:cria_categoria' %} class='texto-btn-finalizar uk-text-capfirst' style='text-decoration:none;color:white;font-size:1.8rem;'>Finalizar</a></button>
                    {% else %}
                        <button type="submit" id='btn-finalizar' class="uk-button uk-button-primary btn-finalizar"><a href={% url 'cadastro:cria_categoria' %} class='texto-btn-finalizar uk-text-capfirst' style='text-decoration:none;color:white;font-size:1.8rem;'> quero Testar minha sorte</a></button>
                    {% endif %}
                    </div>
            </div>

        {% else %}
            <h2 class=''>Desculpe-nos, tivemos um problema com seu carrinho!</h2>
        {% endif %}

    </div>

{% endblock  %}


{% block footer %}
        
{% endblock footer %}

{% block script %}
    <script>
    </script>
{% endblock script %}

compras/templates/compras/view_pages/view_pagina_vendas.html
{% extends 'teste_rifaki/html/base.html' %}   {% load static %}

{% load crispy_forms_tags %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'compras/styles/view_pagina_vendas.css' %}">
    {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'compras/styles/form-style.css' %}"> {% endcomment %}
{% endblock head %}


{% block main %}
{% endblock main %}


{% block content %}
    <div class='uk-position-top-center container-analisador'>
        <div class='row-estatisticas'>
            <div class='contorno-valores'>
                <div class='text-value'>
                    <label class='total-vendidos'>Total de números vendidos: </label>
                </div>
                <div class='value'>
                    <label class='total-vendidos-value'>{{controlador_vendas.getNumeroDeVendidos}}</label>
                </div>                
            </div>

            <div class='contorno-valores'>
                <div class='text-value'>
                    <label class='ainda-pra-vender'>Total de números ainda disponíveis: </label>
                </div>      
                <div class='value'>
                    <label class='ainda-pra-vender-value'>{{controlador_vendas.getNumeroDeRestantes}}</label>
                </div>            
            </div>                

            <div class='contorno-valores'>
                <div class='text-value'>
                    <label class='procetagem-vendas'>Porcentagem de vendas: </label>
                </div>          
                <div class='value'>
                    <label class='procetagem-vendas-value'>{{controlador_vendas.getPorcentagemDeVendas}}%</label>
                </div>       
            </div>

            <div class='contorno-valores'>
                <div class='text-value'>
                    <label class='valor-arrecadado'>Valor arrecadado: </label>
                </div>     
                <div class='value'>
                    <label class='valor-arrecadado-value'>R${{controlador_vendas.getValorArrecadado}}</label>
                </div>             
            </div>
        </div>

        <div class='infos-gerais'>
            <div class='container-recursos'>
                <div class='titulo-box'>
                    <label class='titulo'> Números vendidos </label>
                </div>

                <div class='content-box'>
                {% for numero in controlador_vendas.getNumerosDoCarrinho %}
                    <div class='row-info'>
                        <label class='numeros'>{{numero.numero_escolhido}}</label>
                        <label class='compradores'>{{numero.comprador.username}}  </label>
                    </div>
                {% endfor %}
                </div>                
            </div>
        
            <div class='container-recursos'>
                <div class='titulo-box'>
                    <label class='titulo'> Registrar venda </label>
                </div>

                <div class='content-box'>
                    <div class='row-info'>

                        <form method='post' class='form-group form-block'>
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type='submit' class='black-button'>Registrar</button>
                        </form>
                    </div>
                </div>                
            </div>

            <div class='container-recursos'>
                <div class='titulo-box'>
                    <label class='titulo'> Registrar venda </label>
                </div>

                <div class='content-box'>
                    <div class='row-info'>
                        <input placeholder="Selecione o numero que deseja registrar">
                    </div>
                </div>                
            </div>

        </div>
    </div>
{% endblock  %}


{% block footer %}
        
{% endblock footer %}



{% block script %}
    <script>
        var input_numero_vendido = document.querySelector('#id_numero_vendido');
        input_numero_vendido.setAttribute('type','');
    </script>
{% endblock script %}