cadastro/urls.py
from django.urls import path

from . import views

app_name = 'cadastro'
urlpatterns = [
    path('user/', views.create_user, name='create_user'),
    path('anuncio/', views.cadastro_anuncio, name='cadastro_anuncio'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('<int:anuncio_id>/edit/',
         views.edit_anuncio, name='edit_anuncio'),
    path('profile/password/', views.edit_password, name='edit_password'),
    path('categorias/', views.cria_categoria, name='cria_categoria'),
    path('categorias/list/', views.view_categorias, name='view_categorias'),
    path('categorias/list/<int:categoria_id>/delete/',
         views.delete_categoria, name='delete_categoria'),
    path('categorias/list/<int:categoria_id>/edit/',
         views.edit_categoria, name='edit_categoria'),
]

compras/urls.py
from django.urls import path

from . import views

app_name = 'compras'
urlpatterns = [
    path('carrinho/', views.view_carrinho, name='view_carrinho'),
    path('carrinho/<int:id_NumeroDaSorte>/delete',
         views.delete_do_carrinho, name='delete_do_carrinho'),
    path('<int:anuncio_id>/analisar/',
         views.view_pagina_vendas, name='view_pagina_vendas'),
]

rifaki_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('', include('teste_rifaki.urls')),
    path('firstapp/', include('firstapp.urls')),
    path('admin/', admin.site.urls),
    path('cadastro/', include('cadastro.urls')),
    path('', include("django.contrib.auth.urls")),
    path('compras/', include("compras.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(r'media/(?P<path>.*)$',
            serve, {'document_root':
                    settings.MEDIA_ROOT, }),
    ]

teste_rifaki/urls.py
from django.urls import path

from . import views

app_name = 'teste_rifaki'
urlpatterns = [
    # ex: /teste_rifaki/
    path('', views.index, name='index'),
    # ex: /teste_rifaki/<algum id>
    path('<int:anuncio_id>/', views.detail_anuncio, name='detail'),
    #     # ex: /teste_rifaki/cadastro_anuncio
    path('anuncios/', views.view_profile_anuncios,
         name='view_profile_anuncios'),
]


"""     # ex: /firstapp/algum_id
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /firstapp/algum_id/result
    path('<int:question_id>/result/', views.results, name='result'),
    # ex: /firstapp/algum_id/vote
    path('<int:question_id>/vote/', views.vote, name='vote'), """

cadastro/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django import forms


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    time = timezone.now()
    formato = filename.split('.')[1]
    return 'imagens/carros/anuncio_{0}/{1}'.format(instance.identificador_anuncio, filename)


def removeBlanks(list):
    while("" in list):
        list.remove("")
    return list


class Anuncio(models.Model):
    identificador_anuncio = models.IntegerField()

    TEXT_COLOR_CHOICES = [
        ('black', 'Preto'),
        ('white', 'Branco'),
        ('grey', 'Cinza'),
    ]
    text_color = models.CharField(
        max_length=10,
        choices=TEXT_COLOR_CHOICES,
        default='black',
    )

    titulo_anuncio = models.CharField(max_length=100)

    # marca = models.ChoiceField(choices=c)
    ano_fabricacao = models.IntegerField(default='')

    preco = models.DecimalField(
        max_digits=6, decimal_places=2, default='', error_messages={'invalid': 'Troque a vírgula por ponto!'})

    descricao_breve = models.TextField(max_length=400)
    descricao_completa = models.TextField(max_length=2000)
    anunciante = models.ForeignKey(User, on_delete=models.CASCADE)

    imagem1 = models.ImageField(
        upload_to=user_directory_path, null=False, blank=False, name='imagem1')
    imagem2 = models.ImageField(
        upload_to=user_directory_path, null=True, blank=True, name='imagem2')
    imagem3 = models.ImageField(
        upload_to=user_directory_path, null=True, blank=True, name='imagem3')
    imagem4 = models.ImageField(
        upload_to=user_directory_path, null=True, blank=True, name='imagem4')
    imagem5 = models.ImageField(
        upload_to=user_directory_path, null=True, blank=True, name='imagem5')

    mem_categorias = models.CharField(max_length=1000, null=True)
    data_publi = models.DateTimeField('data publicação')

    # provavelmente teremos que adicionar ao banco de dados, mas primeiro vamos testar no loop
    categoria = ''

    def __str__(self):
        return self.titulo_anuncio + '  ' + str(self.data_publi)

    @property
    def getListOfImages(self):
        list_images = [str(self.imagem1), str(self.imagem2),
                       str(self.imagem3), str(self.imagem4),
                       str(self.imagem5)
                       ]

        return removeBlanks(list_images)

    @property
    def getFirstImage(self):
        return str(self.imagem1)


class Categoria(models.Model):
    nome = models.CharField(max_length=40)
    nome_apresentavel = models.CharField(max_length=40)
    data_de_criacao = models.DateTimeField()
    index = models.IntegerField(default=0)
    criador = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return 'Nome da categoria: ' + str(self.nome) + '| Criada por: ' + str(self.criador)

cadastro/forms.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from .models import Anuncio, Categoria
from django.utils import timezone


class DateInput(forms.DateInput):
    input_type = 'date'


class FormUserCadastro(UserCreationForm):
    data_nascimento = forms.DateField(widget=(DateInput()))

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
            "data_nascimento",
            "password1",
            "password2",
        ]


class FormEditProfile(UserChangeForm):
    data_nascimento = forms.DateField(widget=(DateInput()))

    class Meta:

        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
            "data_nascimento",
            "password",
        ]


class FormChangePassword(PasswordChangeForm):

    class Meta:
        model = User

# eiqNUFyq6MZRe76


class CadastraAnuncio(forms.ModelForm):

    class Meta:
        model = Anuncio
        fields = [
            'text_color', 'titulo_anuncio', 'ano_fabricacao', 'descricao_breve', 'descricao_completa',
            'preco', 'imagem1', 'imagem2', 'imagem3', 'imagem4', 'imagem5'
        ]

    def clean_ano_fabricacao(self):
        ano_fabricacao = self.cleaned_data.get("ano_fabricacao")
        if ano_fabricacao < 1920:
            raise forms.ValidationError(
                'O ano de fabricação deve conter 4 digitos, e ser posterior a 1920'
            )
        if timezone.now().year < ano_fabricacao:
            raise forms.ValidationError(
                'Ano inválido, ainda estamos em ' +
                str(timezone.now().year) + '!'
            )
        return ano_fabricacao


class FormCategoria(forms.ModelForm):

    class Meta:
        model = Categoria
        fields = [
            'nome', 'nome_apresentavel',
        ]

cadastro/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from .forms import FormUserCadastro, CadastraAnuncio, FormEditProfile, FormChangePassword, FormCategoria
from .models import Anuncio, Categoria
from django.contrib.auth import authenticate, login, update_session_auth_hash
from teste_rifaki.myClasses import ControladorCategorias, ControladorExpositor
from django.db.models import Q
from compras.models import Carrinho, NumeroDaSorte

from django.utils import timezone

from django.contrib.auth.forms import PasswordChangeForm


id_atual = 0

controlador_categorias = ControladorCategorias()


# ------------- USER'S VIEWS --------------- #
def create_user(request):
    form = FormUserCadastro(request.POST)
    if request.method == "POST":
        if form.is_valid():
            request.user = form.save(commit=False)
            request.user.m_data_nascimento = request.POST['data_nascimento']
            request.user.save()

            carrinho = Carrinho()
            carrinho.proprietario = request.user
            carrinho.data_ultima_modificacao = timezone.now()
            carrinho.save()

            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],
                                    )
            login(request, new_user)
            return redirect('/')
    else:
        form = FormUserCadastro()

    return render(request, "cadastro/creation_pages/create_user.html", {'form': form})


def view_profile(request):
    if request.user.is_authenticated:
        args = {'usuario': request.user}
        return render(request, "cadastro/view_pages/view_profile.html", args)
    else:
        return redirect('/login')


def edit_profile(request):
    if request.user.is_authenticated:
        user = request.user
        form = FormEditProfile(request.POST, instance=user)
        if request.method == "POST":
            if form.is_valid():
                user = form.save(commit=False)
                print((request.POST['data_nascimento']))
                user.m_data_nascimento = request.POST['data_nascimento']
                user.save()

                return redirect('/cadastro/profile')
            # aplicaInfosAoUser(request.user, form)
        else:
            form = FormEditProfile(instance=request.user)

            form.data_nascimento = request.user.m_data_nascimento
            print(form.data_nascimento)

        return render(request, "cadastro/edit_pages/edit_user.html", {'form': form, 'usuario': user})
    else:
        return redirect('/login')


def edit_password(request):
    if request.user.is_authenticated:
        usuario = request.user
        form = PasswordChangeForm(data=request.POST, user=usuario)
        if request.method == "POST":
            if form.is_valid():
                print('salvado')
                form.save()
                update_session_auth_hash(request, form.user)
                return redirect('/cadastro/profile')
        else:
            form = PasswordChangeForm(user=request.user)
        return render(request, 'cadastro/edit_pages/edit_password.html', {'form': form})
    else:
        return redirect('/login')


# ------------- ANUNCIOS' VIEWS --------------- #
def cadastro_anuncio(request):
    if request.user.is_authenticated:
        global id_atual
        usuario = request.user
        if request.method == "POST" and usuario.is_authenticated:
            form = CadastraAnuncio(request.POST, request.FILES)
            if form.is_valid():
                anuncio = form.save(commit=False)
                anuncio.anunciante = usuario
                anuncio.data_publi = timezone.now()
                controlador_categorias.verificaCategoriasDesteAnuncio(anuncio)
                anuncio.mem_categorias = anuncio.categoria
                anuncio.identificador_anuncio = id_atual+1
                anuncio.save()
                id_atual += 1
                return HttpResponseRedirect(reverse('teste_rifaki:detail', args=(anuncio.id,)))
        else:
            form = CadastraAnuncio()

        return render(request, 'cadastro/creation_pages/create_anuncio.html', {'form': form, 'usuario': usuario})
    else:
        return redirect('/login')


def edit_anuncio(request, anuncio_id):
    if request.user.is_authenticated:
        usuario = request.user
        anuncio = get_object_or_404(Anuncio, pk=anuncio_id)
        # anuncio = Anuncio.objects.get(id=anuncio_id)
        if request.method == "POST":
            form = CadastraAnuncio(
                request.POST, request.FILES, instance=anuncio)
            if form.is_valid():
                anuncio = form.save(commit=False)
                controlador_categorias.verificaCategoriasDesteAnuncio(anuncio)
                anuncio.mem_categorias = anuncio.categoria
                anuncio.save()
                return HttpResponseRedirect(reverse('teste_rifaki:view_profile_anuncios'))
        else:
            form = CadastraAnuncio(instance=anuncio)

        return render(request, 'cadastro/edit_pages/edit_anuncio.html', {'form': form, 'anuncio': anuncio})
    else:
        return redirect('/login')


# ------------- CATEGORIAS' VIEWS --------------- #
def cria_categoria(request):
    if request.user.is_superuser:
        btn_text = 'criar categoria'
        if request.method == 'POST':
            form = FormCategoria(request.POST)
            if form.is_valid():
                categoria = form.save(commit=False)
                categoria.criador = request.user
                categoria.data_de_criacao = timezone.now()
                categoria.save()

                return HttpResponseRedirect(reverse('cadastro:view_categorias'))
        else:
            form = FormCategoria()
        return render(request, 'cadastro/creation_pages/create_categoria.html', {'form': form, 'btn_text': btn_text})

    else:
        return redirect('/')


def delete_categoria(request, categoria_id):
    if request.user.is_superuser:
        categoria = get_object_or_404(Categoria, pk=categoria_id)
        categoria.delete()
        return HttpResponseRedirect(reverse('cadastro:view_categorias'))
    else:
        return redirect('/')


def edit_categoria(request, categoria_id):
    if request.user.is_superuser:
        btn_text = 'salvar'
        categoria = get_object_or_404(Categoria, pk=categoria_id)
        if request.method == 'POST':
            form = FormCategoria(request.POST, instance=categoria)
            if form.is_valid():
                categoria = form.save(commit=False)
                categoria.criador = request.user    # criador ==> editor
                categoria.data_de_criacao = timezone.now()  # data de edição no caso
                categoria.save()

                return HttpResponseRedirect(reverse('cadastro:view_categorias'))
        else:
            form = FormCategoria(instance=categoria)
        return render(request, 'cadastro/creation_pages/create_categoria.html', {'form': form, 'btn_text': btn_text})

    else:
        return redirect('/')


def view_categorias(request):
    if request.user.is_superuser:
        lista_categorias_existentes = Categoria.objects.all()
        return render(request, 'cadastro/view_pages/view_categorias.html', {'lista_categorias_existentes': lista_categorias_existentes})
    else:
        return redirect('/')

cadastro/templates/cadastro/view_pages/view_categorias.html
{% extends 'teste_rifaki/html/base.html' %}   {% load static %}

{% load crispy_forms_tags %}


{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'cadastro/styles/form-style.css' %}">
{% endblock head %}


{% block main %}
    <div id="main" class="user">
{% endblock main %}


{% block content %}
    <div class='sec-form uk-position-top-left'>
        <h2>Lista de categorias</h2>
         <table class="uk-table uk-table-striped table">
            <tbody class='informacoes-user' style='list-style:none;'>
                <tr>
                    <td class='row-titulo-base'>Nome</td>
                    <td class='row-titulo-base'>Código</td>
                    <td class='row-titulo-base' ></td>
                    <td class='row-titulo-base' ></td>
                </tr>
                {% for categoria in lista_categorias_existentes %}
                    <tr>            
                        <td class='item-info' style='color:grey; font-weight:700;'>{{categoria.nome_apresentavel}}</td>
                        <td class='item-info' style='color:grey; font-weight:700;'>{{categoria.nome}}</td>
                        <td><button type="submit" id='btn-excluir' class="btn-ver-carrinho uk-button uk-button-primary"><a href='{{categoria.id}}/edit' class='nome uk-text-uppercase' style='text-decoration:none;color:white;'>Editar</a></button></td>
                        <td><button type="submit" id='btn-excluir' class="btn-ver-carrinho uk-button uk-button-primary"><a href='{{categoria.id}}/delete' class='nome uk-text-uppercase' style='text-decoration:none;color:white;'>Excluir</a></button></td>
                    </tr>
                {% endfor %}    
            </tbody>  
        </table>
        <button type="submit" id='btn-excluir' class="btn-ver-carrinho uk-button uk-button-primary"><a href={% url 'cadastro:cria_categoria' %} class='nome uk-text-uppercase' style='text-decoration:none;color:white;'>Adicionar categoria</a></button>
    </div>
{% endblock  %}


{% block footer %}
        
{% endblock footer %}

{% block script %}
    <script>
        btn_excluir = document.getElementById('btn-excluir');

        btn_excluir.onclick = () => {

        }
    </script>
{% endblock script %}

cadastro/templates/cadastro/view_pages/view_profile.html
{% extends 'teste_rifaki/html/base.html' %}   {% load static %}

{% load crispy_forms_tags %}


{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'cadastro/styles/profile.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'cadastro/styles/form-style.css' %}">
{% endblock head %}


{% block main %}
{% endblock main %}


{% block content %}
    <div class='sec-form uk-position-top-center'>
        <div class='uk-card uk-card-default o-card'>
            <div class='uk-card-title'>
                 <h1 class ='uk-position-top-center uk-text-uppercase sua-conta'>Sua conta</h1>
            </div>
           
            <div class='uk-card-body card-body'>
                <table class="uk-table uk-table-striped table">
                    <tbody class='informacoes-user' style='list-style:none;'>
                        <tr>            
                            <td class='nome uk-text-uppercase' style='color:white;'>Nome: </td>
                            <td class='nome-user uk-text-uppercase' style='color:white;'>{{ usuario.first_name }}</td>
                        </tr>
                        <tr>            
                            <td class='sobrenome uk-text-uppercase' style='color:white;'>Sobrenome: </td>
                            <td class='sobrenome-user uk-text-uppercase' style='color:white;'>{{ usuario.last_name }}</td>
                        </tr>
                        <tr>            
                            <td class='username uk-text-uppercase' style='color:white;'>Usuário: </td>
                            <td class='username-user uk-text-uppercase' style='color:white;'>{{ usuario.username }}</td>
                        </tr>
                        <tr>            
                            <td class='data_nascimento uk-text-uppercase' style='color:white;'>Data de nascimento: </td>
                            <td class='data_nascimento-user uk-text-uppercase' style='color:white;'>{{ usuario.m_data_nascimento }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class='uk-card-footer card-footer-meu'>
                <div class='group-buttons'>
                    <button class='uk-button uk-button-secondary btn-meus-anuncios uk-text-uppercase'><a href="{% url 'teste_rifaki:view_profile_anuncios' %}">Meus anuncios</a></button>
                    <button class='uk-button uk-button-secondary btn-edit uk-text-uppercase' ><a href="{% url 'cadastro:edit_profile' %}">Editar perfil</a></button>    
                </div>
                
            </div>
        </div>
    </div>
{% endblock %}


{% block footer %}
        
{% endblock footer %}

{% block script %}
    <script>
    {% comment %} 
        var input_Nome = document.getElementsById('id_first_name')
        var input_sNome = document.getElementsById('id_last_name')
        var input_user = document.getElementsById('id_username')
        var input_email =  document.getElementsById('id_email')
        var inpu_dNascimento = document.getElementsById('id_data_nascimento') 
        var input_senha = document.getElementsById('id_password1') 

        function addPlaceholder(input_guy):
            input_guy.placeholder ="{{ user.get }}"; 
    {% endcomment %}
        {% comment %} var btn_meusAnuncios = document.getElementsByClassName('.btn-meus-anuncios')

        btn_meusAnuncios.onclick = function (){

        } {% endcomment %}

    </script> 
{% endblock script %}